[project]
name = ""
version = "0.1.0"
description = "Add a short description here"
authors = ["kashi-x <kashimiya.exe@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
lab = "jupyter lab"

[dependencies]
python = "3.12.*"
returns = ">=0.22.0,<0.23"
rich = ">=13.7.1,<13.8"
structlog = ">=24.1.0,<24.2"
pendulum = ">=3.0.0,<3.1"
yarl = ">=1.9.4,<1.10"
jupyterlab = ">=4.2.1,<4.3"
ruff = ">=0.4.5,<0.5"

[pypi-dependencies]
better-exceptions = "*"


# [feature.test.dependencies]
# pytest = ">=7.2.0,<8.3"
# coverage = ">=7.5.2,<7.6"
